name: .NET Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v4
    - name: Setup .NET 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore "./src"
    - name: Build code
      run: dotnet build "./src" --configuration Release --no-restore
    - name: Publish application
      run: dotnet publish "./src" -c Release -o MgcPrxyDrftr --runtime win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
       name: MgcPrxyDrftr
       path: "./src" 
